sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: oqo7w6ArfN/pcn+KmvBim7TsvllvmTJDgTyUsvXhorFEOIJ04QA1Z6zoEumHJNgjePYTqgOTVDablwktSzXjB/rMXfKSz9LCDBV8e0cY/vVoa+8nZ19zATDPsoYDc/No1G3L3USUp1VoVqK8q+385PLXbRTeRXeqRrV4jZjBqwcuYMgQF7jJ4XdQbNjfZXjAnUJ4L3iLNTEg+2NE+Y1C9CTpyL37xbZkW8bsIAGtAVYFOdlkn+iVO+v8iKWgJ/0m2lssg4KMRu5ALLiMiVWj3anJBUGrRP9ywpAuSJstTv5BpsRMejLg38L9ARZ1ZxK6XpFlGCBN4QQUQQu2FEBKz3DHFDs+TMK/o7VjXhnmMoAMtMhBZSZ6JES7iXl11nFODPA5NVgxyfsALqhADc8GG4I4xxR2v6z0q8vWSlxRiLvSTcKddJv5Yo/4HWfq3Z/gBKir1EhZ1x0kMzYHxTtz8+8x2AOeXpPuXEa1U3Ex0LpFjPP46o23vWHnO0WrhLiecwnVQ7X8a7ZYpZuygf9JbXTfc3BgIBwSgez99gcbXnv+QuHccuDTFz/oPCDstXZR/qgl9ZmPLjpo+tpQhLfh6cpKWKSXwnlUh4fGWc37NC1VGOnbS7SFW/KFocBAzQduhtsTMIvn2qlx2h3g1fMYObC/jMiBTvWnRWVbWUF3BRg=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Discourse-on-the-Method-of-Rightly-Conducting-One-s-Reason-and-of-Seeking-Truth-in-the-Sciences_59
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy